### ISSUE TITLE
add option to exclude dev and build dependencies

### ISSUE THREAD

**Issue by piotr-sk** [coreos/cargo-vendor-filterer#101]
We use this crate to filter out sources that do not need full software clearing,
so are not interested in the dev or build dependencies.

It is possible to identify these clearly with `cargo tree` by specifying `--edges normal` flag (other potentially interesting options: no-build, no-dev, no-proc-macro).
Unfortunately, the flag is not available with `cargo metadata` as discussed in <https://github.com/rust-lang/cargo/issues/10718>.

Proposition: add an optional boolean flag `--exclude-dev-and-build-deps` to cargo vendor filterer (alternative: mimic cargo tree edges options).
If the flag is set, after removing the unwanted platforms and tiers, call `cargo tree` to get a list of packages required for the application with all features.
Iterate over the packages HashMap and remove all entries not present in the list received from `cargo tree`.

Expected behavior when running on the crate itself: when the flag is set the `once_cell` dev package shall be removed -> add a unit test.

By default the flag is not active for backwards compatibility.

Current workaround: manually remove development crates (it is annoying)

Let me know what you think and if you agree that this is a good extension for the current crate, I can send a PR implementing this feature.

**Comment by cgwalters** [comment]
The feature generally makes sense to me, although right now this project is intending to be roughly CLI compatible with `cargo vendor`.

I think we should at least propose the feature there first?

**Comment by piotr-sk** [comment]
You're right. I've created https://github.com/rust-lang/cargo/issues/14654 and will see how easy it be to get it approved and done in the cargo vendor directly.
