### ISSUE TITLE
new tag providing recent features to crate users

### ISSUE THREAD

**Issue by piotr-sk** [coreos/cargo-vendor-filterer#103]
Two new features landed recently: 
- https://github.com/coreos/cargo-vendor-filterer/pull/97
- https://github.com/coreos/cargo-vendor-filterer/pull/99 

There is one in review https://github.com/coreos/cargo-vendor-filterer/pull/102 and hopefully can be merged soon.

Can we make a new tag of this crate providing them to crate users?
Thanks in advance.

/cc @cgwalters

**Comment by cgwalters** [comment]
This was done.
