### ISSUE TITLE
Output tarball does not wrap crate directories in a containing directory

### ISSUE THREAD

**Issue by bgilbert** [coreos/cargo-vendor-filterer#27]
`cargo vendor` produces an output directory (defaulting to `vendor`) which contains a subdirectory for each of the crates being vendored.  It's been our practice in CoreOS projects to tar up that directory and ship the tarball as a release artifact, so that downstream distro packages can build the project without individually fetching dependencies.

Tarballs produced by cargo-vendor-filterer don't serve as a drop-in replacement for this practice, since the crate directories are directly placed in the root of the tarball instead of in a `vendor` subdirectory.  This causes problems for a couple reasons:

- The downstream package needs to adjust its unpacking code to do `mkdir vendor && tar xf vendor.tgz -C vendor` instead of just `tar xf vendor.tgz`, which is a needless compatibility break.
- It's generally an antipattern to distribute tarballs which, unless special attention is paid during unpacking, create many entries in the current working directory.

There doesn't seem to be any way to configure this behavior, other than by avoiding `--format tar*` and packing the resulting tarball manually.

**Comment by cgwalters** [comment]
PR in https://github.com/coreos/cargo-vendor-filterer/pull/29
