### ISSUE TITLE
Fails on `kernel32-sys` and `advapi32-sys`

### ISSUE THREAD

**Issue by iv-m** [coreos/cargo-vendor-filterer#32]
`cargo vendor-filterer`  fails to replace certain crates, like  `kernel32-sys` or `advapi32-sys`, because `cargo metadata` fails on the vendored crates.

Steps to reproduce:

```console
$ cargo new just-test
     Created binary (application) `just-test` package
$ cd just-test
$ cargo add local-encoding
    Updating crates.io index
      Adding local-encoding v0.2.0 to dependencies.
$ cargo vendor-filterer --platform x86_64-unknown-linux-gnu
Gathering metadata for platforms
   Vendoring fuchsia-cprng v0.1.1 (/crypt/iv/.cargo/registry/src/github.com-1ecc6299db9ec823/fuchsia-cprng-0.1.1) to vendor/fuchsia-cprng
   Vendoring getopts v0.2.21 (/crypt/iv/.cargo/registry/src/github.com-1ecc6299db9ec823/getopts-0.2.21) to vendor/getopts
   Vendoring kernel32-sys v0.2.2 (/crypt/iv/.cargo/registry/src/github.com-1ecc6299db9ec823/kernel32-sys-0.2.2) to vendor/kernel32-sys
   Vendoring libc v0.2.135 (/crypt/iv/.cargo/registry/src/github.com-1ecc6299db9ec823/libc-0.2.135) to vendor/libc
   Vendoring local-encoding v0.2.0 (/crypt/iv/.cargo/registry/src/github.com-1ecc6299db9ec823/local-encoding-0.2.0) to vendor/local-encoding
   Vendoring pulldown-cmark v0.0.3 (/crypt/iv/.cargo/registry/src/github.com-1ecc6299db9ec823/pulldown-cmark-0.0.3) to vendor/pulldown-cmark
   Vendoring rand v0.4.6 (/crypt/iv/.cargo/registry/src/github.com-1ecc6299db9ec823/rand-0.4.6) to vendor/rand
   Vendoring rand_core v0.3.1 (/crypt/iv/.cargo/registry/src/github.com-1ecc6299db9ec823/rand_core-0.3.1) to vendor/rand_core-0.3.1
   Vendoring rand_core v0.4.2 (/crypt/iv/.cargo/registry/src/github.com-1ecc6299db9ec823/rand_core-0.4.2) to vendor/rand_core
   Vendoring rdrand v0.4.0 (/crypt/iv/.cargo/registry/src/github.com-1ecc6299db9ec823/rdrand-0.4.0) to vendor/rdrand
   Vendoring remove_dir_all v0.5.3 (/crypt/iv/.cargo/registry/src/github.com-1ecc6299db9ec823/remove_dir_all-0.5.3) to vendor/remove_dir_all
   Vendoring skeptic v0.4.0 (/crypt/iv/.cargo/registry/src/github.com-1ecc6299db9ec823/skeptic-0.4.0) to vendor/skeptic
   Vendoring tempdir v0.3.7 (/crypt/iv/.cargo/registry/src/github.com-1ecc6299db9ec823/tempdir-0.3.7) to vendor/tempdir
   Vendoring unicode-width v0.1.10 (/crypt/iv/.cargo/registry/src/github.com-1ecc6299db9ec823/unicode-width-0.1.10) to vendor/unicode-width
   Vendoring winapi v0.2.8 (/crypt/iv/.cargo/registry/src/github.com-1ecc6299db9ec823/winapi-0.2.8) to vendor/winapi-0.2.8
   Vendoring winapi v0.3.9 (/crypt/iv/.cargo/registry/src/github.com-1ecc6299db9ec823/winapi-0.3.9) to vendor/winapi
   Vendoring winapi-build v0.1.1 (/crypt/iv/.cargo/registry/src/github.com-1ecc6299db9ec823/winapi-build-0.1.1) to vendor/winapi-build
   Vendoring winapi-i686-pc-windows-gnu v0.4.0 (/crypt/iv/.cargo/registry/src/github.com-1ecc6299db9ec823/winapi-i686-pc-windows-gnu-0.4.0) to vendor/winapi-i686-pc-windows-gnu
   Vendoring winapi-x86_64-pc-windows-gnu v0.4.0 (/crypt/iv/.cargo/registry/src/github.com-1ecc6299db9ec823/winapi-x86_64-pc-windows-gnu-0.4.0) to vendor/winapi-x86_64-pc-windows-gnu
To use vendored sources, add this to your .cargo/config.toml for this project:


[source.crates-io]
replace-with = "vendored-sources"

[source.vendored-sources]
directory = "vendor"
Skipping just-test
Replacing unreferenced package with stub: winapi-x86_64-pc-windows-gnu
Replacing unreferenced package with stub: winapi-i686-pc-windows-gnu
Replacing unreferenced package with stub: winapi-build
Replacing unreferenced package with stub: winapi
error: Replacing with stub: winapi-0.2.8: Executing cargo metadata: Error during execution of `cargo metadata`: error: failed to load manifest for dependency `advapi32-sys`

Caused by:
  failed to read `/tmp/.private/iv/just-test/vendor/winapi-0.2.8/lib/advapi32/Cargo.toml`

Caused by:
  No such file or directory (os error 2)
```

Same error, but with `kernel32-sys` vendored crate, happens when trying to vendor dependencies for https://github.com/mozilla/sccache checked out to  tag `v0.3.0`.

**Comment by iv-m** [comment]
Oh, sorry, it was not  advapi, it was  `winapi-0.2.8` in my test example which caused failure. Anyway, the problem is that crate dependencies (or dev-dependencies) have  path specified, and this path does not exist when the crate is vendored:

https://github.com/retep998/winapi-rs/blob/77588710a683e1a4ec085b0f3d6c8939ecc7f030/Cargo.toml

**Comment by cgwalters** [comment]
It looks like https://github.com/retep998/winapi-rs/commit/246dfcb3bd068ce354448877c4c59d8b10075285 is the commit that fixed this.

Working around this is going to be really hacky.  Perhaps we could just special case this crate?  Or maybe we could neuter all `dev-dependencies` by default?

**Comment by iv-m** [comment]
One way to work around this is to remove all the dependencies (or just their paths?) in the same way `[workspace]` section is injected. It is convenient to do this using `toml_edit` crate. I have a working prototype for that and I can submit a pull request.

Another interesting option is to copy `[package]` section from original `Cargo.toml` as is (maybe dropping a few fields like `build` and `links`), without turning to cargo to parse it.

WDYT?

**Comment by cgwalters** [comment]
Hmm...my inclination here is to write code that targets this as a special case instead of trying to wholesale filter the `Cargo.toml`.  Unless we see evidence that this applies more widely.  (I guess we could write code that just compares success rate of `cargo vendor` versus `cargo vendor-filterer` on many projects)

Though, one thing is confusing me right now.  Looking at e.g. tokio, I see:
https://github.com/tokio-rs/tokio/blob/74a29be6077f4093373c647a2e3834bb5e2e9cd7/tokio/Cargo.toml#L144
So here we have a `dev-dependency` that uses `path`.  However...the published `Cargo.toml` is different.  https://docs.rs/crate/tokio/1.21.2/source/Cargo.toml

I wonder if something on the crates.io publish process ended up fixing this, but only for newer crates?

**Comment by cgwalters** [comment]
Ah, OK I see it's https://github.com/rust-lang/cargo/blob/810cbad9a123ad4ee0a55a96171b8f8478ff1c03/src/cargo/util/toml/mod.rs#L1349

There's a whole lot of stuff going on in that function, but I'd bet :money_with_wings: that at some point the logic in cargo changed to filter out `dev-dependencies` with path references or so.

**Comment by cgwalters** [comment]
OK I took a crack at this https://github.com/coreos/cargo-vendor-filterer/pull/38 but it's more complex than I thought because of the interplay between `dev/build-dependencies` and features.

**Comment by cgwalters** [comment]
Can you give https://github.com/coreos/cargo-vendor-filterer/pull/43 a whirl?  I think this approach is both simple and viable, and it fixes the case here.

**Comment by cgwalters** [comment]
@iv-m Hi, this is released in https://crates.io/crates/cargo-vendor-filterer/0.5.8 - please let me know if it doesn't work!

**Comment by iv-m** [comment]
> @iv-m Hi, this is released in https://crates.io/crates/cargo-vendor-filterer/0.5.8 - please let me know if it doesn't work!

`cargo-vendor-filterer` 0.5.8 works for me. Thank you so much, @cgwalters!
