### ISSUE TITLE
Multiple --platform= options

### ISSUE THREAD

**Issue by vt-alt** [coreos/cargo-vendor-filterer#44]
Is there way to specify multiple platforms from command line?
When I try `cargo vendor-filterer --platform='*'-unknown-linux-gnu` (for `sequoia-sop`) here is error:
```
  error: Could not create LLVM TargetMachine for triple: m68k-unknown-linux-gnu: No available targets are compatible with triple "m68k-unknown-linux-gnu"
```
When I try to specify multiple `--platform=` options like:
```
     --platform=aarch64-unknown-linux-gnu \
     --platform=armv7-unknown-linux-gnueabihf \
     --platform=i686-unknown-linux-gnu \
     --platform=powerpc64le-unknown-linux-gnu \
     --platform=x86_64-unknown-linux-gnu
```
It does not compile on x86_64, perhaps something superfluous is filtered.

**Comment by JackWolfard** [comment]
This would be a nice feature to have +1

**Comment by cgwalters** [comment]
I think this is a dup of https://github.com/coreos/cargo-vendor-filterer/issues/50 (which I filed later since I missed this, but I believe the information there is more accurate).

> It does not compile on x86_64, perhaps something superfluous is filtered.

Which project is this?  Can you give more information about the compilation failure?

**Comment by vt-alt** [comment]
It was for [`sequoia-sop`](https://gitlab.com/sequoia-pgp/sequoia-sop). It was 2 months ago so I don't remember much details. I will write more when I return to it.

**Comment by cgwalters** [comment]
Closing as a dup of https://github.com/coreos/cargo-vendor-filterer/issues/50
