### ISSUE TITLE
Support for sharing vendor directory between multiple projects (`--sync` from cargo-vendor)

### ISSUE THREAD

**Issue by JackWolfard** [coreos/cargo-vendor-filterer#53]
cargo vendor supports `--sync` parameter:
```sh
$ cargo vendor --help | rg sync
    -s, --sync <TOML>            Additional `Cargo.toml` to sync and vendor
```

With this parameter, multiple projects can share the same vendor directory. One complication could be if users want projects which have different platforms but overlapping dependencies to share a directory (#44).

I am willing to contribute this feature.

**Comment by cgwalters** [comment]
In general I think we should aim to be a drop-in replacement for `cargo vendor`, so every feature like this makes sense to me.

> One complication could be if users want projects which have different platforms but overlapping dependencies to share a directory (https://github.com/coreos/cargo-vendor-filterer/issues/44).

We should just take the union of the filters, right?

> I am willing to contribute this feature.

Cool!  Feel free to push a "WIP" style pull request and I'm happy to help review and merge!

**Comment by kgrech** [comment]
Thanks @JackWolfard, I also need quite this urgently and I am happy to contribute it as well. When would you have time to work on it? Let me know if you need help with it.

**Comment by kgrech** [comment]
> We should just take the union of the filters, right?

I wish [cargo metadata](https://doc.rust-lang.org/cargo/commands/cargo-metadata.html) would just have ``-sync`` as well, but it does not :(

**Comment by JackWolfard** [comment]
> Thanks @JackWolfard, I also need quite this urgently and I am happy to contribute it as well. When would you have time to work on it? Let me know if you need help with it. 

I plan to work on it today. Once I open a PR, we can have further discussion there. If you need it quicker than that, feel free to start on it.

**Comment by kgrech** [comment]
It is totally fine. HUGE thanks for taking care of it!
