### ISSUE TITLE
Integrate testing into `cargo test`

### ISSUE THREAD

**Issue by JackWolfard** [coreos/cargo-vendor-filterer#56]
The current testing method is through a shell script. Previous work from `cargo-vendor`<sup>[1](https://github.com/alexcrichton/cargo-vendor/blob/07570e23d0841936cea8af2a125484f4d10ccdfa/tests/vendor.rs)</sup>, and `cargo`<sup>[2](https://github.com/rust-lang/cargo/blob/e7b11e733d7c925c79520f2621e6cd50f6c65e34/tests/testsuite/vendor.rs), [3](https://github.com/rust-lang/cargo/tree/master/crates/cargo-test-support)</sup> allow for suitable mocking to embed tests directly in Rust.

First discussed with @cgwalters in [this PR thread](https://github.com/coreos/cargo-vendor-filterer/pull/55#issuecomment-1448172929).

**Comment by cgwalters** [comment]
This was done in https://github.com/coreos/cargo-vendor-filterer/pull/58
