### ISSUE TITLE
`--format=tar` fails on MacOS

### ISSUE THREAD

**Issue by JackWolfard** [coreos/cargo-vendor-filterer#57]
When running the command `cargo vendor-filterer --format=tar vendor.tar`, I get the following error on MacOS 13.2:

```
tar: Option --sort=name is not supported
Usage:
  List:    tar -tf <archive-filename>
  Extract: tar -xf <archive-filename>
  Create:  tar -cf <archive-filename> [filenames...]
  Help:    tar --help
error: tar failed: ExitStatus(unix_wait_status(256))
```

My `tar` version is `bsdtar 3.5.3 - libarchive 3.5.3 zlib/1.2.11 liblzma/5.0.5 bz2lib/1.0.8`.

To remedy this, I would suggest relying on the following crates instead of calling the system `tar` using [`std::process::Command`](https://doc.rust-lang.org/std/process/struct.Command.html):

- [tar](https://crates.io/crates/tar): reader and writer for tar files
- [flate2](https://crates.io/crates/flate2): gzip compression
- [zstd](https://crates.io/crates/zstd): bindings for zstd compression

**Comment by cgwalters** [comment]
I think of these things, the main one to fix is using the `tar` crate instead; the compression would be another step where we could still use system binaries if they exist (this would avoid us linking to libzstd for example).

**Comment by cgwalters** [comment]
I did https://github.com/coreos/cargo-vendor-filterer/pull/65 which is a step towards this, because we definitely can't rely on the CLI tools on Windows.

**Comment by cgwalters** [comment]
OK, and https://github.com/coreos/cargo-vendor-filterer/pull/66 should get us farther.  @JackWolfard mind testing/reviewing?

**Comment by JackWolfard** [comment]
> OK, and #66 should get us farther. @JackWolfard mind testing/reviewing?

Yes, I will review this today

**Comment by cgwalters** [comment]
Closing this as fixed by https://github.com/coreos/cargo-vendor-filterer/pull/66
