### ISSUE TITLE
missing dependencies in vendor dir

### ISSUE THREAD

**Issue by Luap99** [coreos/cargo-vendor-filterer#75]
I am not sure what causes this but with netavark 1.8.0 at least one required dependency was removed from the vendor dir

At the very least `event-listener@2.5.3` was removed despite being used.
```
$ cargo tree -i event-listener@2.5.3
event-listener v2.5.3
├── async-broadcast v0.5.1
│   └── zbus v3.14.1
│       └── netavark v1.8.0 (/home/pholzing/CODE/netavark)
├── async-channel v1.9.0
│   └── blocking v1.4.0
│       ├── async-fs v1.6.0
│       │   └── zbus v3.14.1 (*)
│       └── zbus v3.14.1 (*)
├── async-lock v2.8.0
│   ├── async-executor v1.5.3
│   │   └── zbus v3.14.1 (*)
│   ├── async-fs v1.6.0 (*)
│   ├── async-io v1.13.0
│   │   └── zbus v3.14.1 (*)
│   ├── blocking v1.4.0 (*)
│   └── zbus v3.14.1 (*)
└── zbus v3.14.1 (*)
```
```
...
Replacing unreferenced package with stub: event-listener-2.5.3
...
```

I am not sure why it thinks that it is not used, netavark depends on zbus 3.14.1 and it depends on event-listener 2.5.3
https://github.com/containers/netavark/blob/8309b68113918f9e2b178892a73ea802cdca3151/Cargo.toml#L48
https://github.com/dbus2/zbus/blob/6af95ac2e60ffb02ad4633974eb8a04783719589/zbus/Cargo.toml#L53

Original report: https://github.com/containers/netavark/issues/819

**Comment by cgwalters** [comment]
I think what's going on here is this:

```
$ cargo tree -i event-listener
error: There are multiple `event-listener` packages in your project, and the specification `event-listener` is ambiguous.
Please re-run this command with `-p <spec>` where `<spec>` is one of the following:
  event-listener@2.5.3
  event-listener@3.0.0
```

And in `Cargo.lock` they're both present.  However, `event-listener@3.0.0` is only depended on by `async-process`, which gets filtered out because it's [macos only](https://github.com/dbus2/zbus/blob/278f856dcb893f77045cae3d377fd28d4ac27c3e/zbus/Cargo.toml#L107-L110).

Right now we only do a "one pass" filter, I think to fix this this we may need to iterate to a fixed point.

**Comment by cgwalters** [comment]
Actually I was wrong...I think it's more that how we handle package versions is just breaking when we're filtering out the newer package.  Looking at this...

**Comment by cgwalters** [comment]
PR in https://github.com/coreos/cargo-vendor-filterer/pull/76 (I tested it, but feel free to do so as well...I may try to add netavark to the revdep testing, but will have to plow through the capnproto dep).

**Comment by Luap99** [comment]
Can confirm it is working now, thanks for the quick fix and the new release.
