### ISSUE TITLE
Add the ability to specify arguments for `cargo vendor`

### ISSUE THREAD

**Issue by Wardenfar** [coreos/cargo-vendor-filterer#82]
I need to specify the argument `--respect-source-config` for the `cargo vendor` command that is executed by `cargo vendor-filterer`.

I saw a similar case for the `--offline` argument.

I see two ways to fix this :

1. Add another flag like `--offline`

2. Fix it in a more general way, for example : `cargo vendor-filterer --platform ... -- --respect-source-config --other-cargo-vendor-flag`

What do you prefer ?

I will be happy to submit a PR.

**Comment by cgwalters** [comment]
I weakly lean towards option 1 ("reimplement option") - we haven't had the need for many of these yet (AFAIK) and it seems a bit nicer to have our `--help` be useful.

But OTOH if you feel even mildly strongly about doing option 2 that's totally fine by me!

(These aren't mutually exclusive obviously; we can do both!)
